### ISSUE TITLE
Package Agda 2.6.4

### ISSUE THREAD

**Issue by andreasabel** [wenkokke/setup-agda#196]
Would be great if Agda 2.6.4 was supported.
Standard libraries 1.7.1/2 work _mostly_ with Agda 2.6.4, but some modules do not build because they would need `--large-indices`.  
~~Maybe you want to await 1.7.3 of the library, although installing Agda without the library also has uses.~~

Update: @MatthewDaggitt just released 1.7.3 of the standard library!

**Comment by wenkokke** [comment]
My eventual plan is to deprecate this action in favor of a much simpler action which installs [agda-python](https://github.com/wenkokke/agda-python), due to the ease of maintenance: It's _much less_ code, and gets distribution via PyPI for free!

My only concerns are:
- The Python distribution does not support cluster counting on all platforms.
- The Python distribution does not support installing libraries.

I'm looking into solutions for the former. (Ultimately, I believe we should drop the dependency on `text-icu`.)

The latter, I believe, should be solved by the Agda project, e.g., by supporting an `agda pkg install` command such that `agda pkg install <url to archive>` downloads and extracts the archive and adds it to the libraries file.

However, I'm happy to continue supporting the next few releases.

**Comment by wenkokke** [comment]
This should be working now :)
